name: Lint with Ruff

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          
      - name: Install PDM
        run: python -m pip install pdm

      - name: Install Ruff
        run: |
          pdm install

      - name: Run Ruff
        run: pdm run ruff .
